liongram/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from posts.views import class_view, function_view, index, url_parameter_view, url_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path

from posts.views import post_create_form_view, post_create_view, post_delete_view, post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)
    

liongram/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as DjangoUserManager

# class UserInfo(models.Model):
#     phone_sub = models.CharField(verbose_name='보조 전화번호', max_length=11)
#     user = models.ForeignKey(to='User', on_delete=models.CASCADE)

class UserManager(DjangoUserManager):
    def _create_user(self, username, email, password, **extra_fields):
        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(username, email, password, extra_fields)
        
class User(AbstractUser):
    phone = models.CharField(verbose_name='전화번호', max_length=11)
    objects = UserManager()

liongram/posts/forms.py
from django import forms

from posts.models import Post

# class PostBaseForm(forms.Form):
#     image = forms.ImageField(label='이미지')
#     content = forms.CharField(label='내용', widget=forms.Textarea)

class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        models = Post
        fields = ['image', 'content']

liongram/posts/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from django.views.generic import ListView
from posts.forms import PostBaseForm, PostCreateForm

from posts.models import Post

def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list': post_list,
    }
    return render(request, 'index.html', context)

def post_list_view(request):
    post_list = Post.objects.all()
    # Post.objects.filter(writer=request.user) # 현재 로그인한 사용자의 게시글 조회
    context = {
        'post_list': post_list,
    }
    return render(request, 'posts/post_list.html', context)

def post_detail_view(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'posts/post_detail.html', {'post': post})

# @login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    elif request.method == 'POST':
        image = request.FILES.get('image')
        content = request.POST.get('content')
        Post.objects.create(
            image=image,
            content=content,
            # writer=request.user,
        )
        return redirect('index')
    
def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {'form': form}
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostBaseForm(request.POST, request.FILES)
        if form.is_valid():
            Post.objects.create(
                image=form.cleaned_data['image'],
                content=form.cleaned_data['content'],
                writer = request.user,
            )
        return redirect('index')

def post_update_view(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'GET':
        context = {
            'post': post,
        }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        image = request.FILES.get('image')
        content = request.POST.get('content')
        if image:
            post.image.delete()
            post.image = image
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'GET':
        return render(request, 'posts/post_confirm_delete.html', {'post': post})
    elif request.method == 'POST':
        post.delete()
        return redirect('index')


def url_view(request):
    return HttpResponse('<h1>url view</h1>')
    # return JsonResponse({'name': 'Jiseok'})

def url_parameter_view(request, username):
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method: {request.method}')
    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

class class_view(ListView):
    model = Post
    template_name = 'cbv_view.html'

liongram/users/views.py
from django.shortcuts import render

# Create your views here.

liongram/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        <p>{{ object }}</p>
    {% endfor %}
</body>
</html>

liongram/posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>function based view</h1>
    <a href="/fbv/">새로고침</a>
    <form action="" method="GET">
        <input type="text" name="var">
        <input type="submit" value="GET submit">
    </form>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="var">
        <input type="submit" value="POST submit">
    </form>
</body>
</html>

liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static '' %}">
    <link rel="stylesheet" href="{% static '' %}"> -->
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icon/home_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="홈">
                    </a>
                </li>
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icon/search_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="검색">
                    </a>
                </li>
                <li>
                    <a href="{% url 'posts:post-create' %}">
                        <img src="{% static 'icon/add_box_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="글쓰기">
                    </a>
                </li>
                <li><img src="{% static 'icon/favorite_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="좋아요"></li>
                <li><img src="{% static 'icon/account_circle_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="프로필"></li>
            </ul>
        </nav>
    </div>
</body>
</html>

liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}홈{% endblock %}

{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False%}
        {% endfor %}
    </div>
</main>
{% endblock %}

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img src="https://via.placeholder.com/32x32" alt="프로필">
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
        {%if request.user == post.writer%}
            <a href="{% url 'posts:post-update' post.id %}">수정하기</a>
            <a href="{% url 'posts:post-delete' post.id %}">삭제하기</a>
        {%endif%}
    </div>
    <div class="card__body">
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}" alt="">
            {% else %}
                <img class="card__image" src="https://via.placeholder.com/600x600" alt="">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <img class="card__btn" src="{% static 'icon/favorite_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="">
            <img class="card__btn" src="{% static 'icon/chat_bubble_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="">
            <img class="card__btn" src="{% static 'icon/send_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="">
            <img class="card__btn" src="{% static 'icon/bookmark_FILL0_wght400_GRAD0_opsz48.svg' %}" alt="">
            <!--  -->
        </div>
        <div>
            <!-- <img class="card__btn" src="{% static 'icon/bookmark_FILL0_wght400_GRAD0_opsz48.svg' %}" alt=""> -->
        </div>
    </div>
    <div class="card_content">
        <span class="card__line-num">좋아요 00개</span>
        <div class="card__main-text">
            <p>
                <span class="card__user-name">{{ post.writer }}</span>
                {%if not detail%}
                    {{post.content|truncatechars:35}}
                {%else%}
                    {{post.content}}
                {%endif%}
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
                {% endif %}
            </p>
        </div>
        <div>
            <p>
                댓글 {{ post.comment_set.all.count }}개
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                {% endif %}
            </p>
            <ul class="card__comment-group">
                {% if not detail %}
                    {% for comment in post.comment_set.all|slice:":2" %}
                    <li>
                        <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                {% else %}
                    {% for comment in post.comment_set.all %}
                    <li>
                        <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                {% endif %}
            </ul>
            <p class="card__created_at">{{ post.created_at|date:"Y년 m월 d일"}}</p>
        </div>
    </div>
</div>

liongram/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}삭제{% endblock %}
{% block content %}
<h1>Post 삭제 화면</h1>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
</form>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

liongram/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}상세{% endblock %}
{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

liongram/templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %}입력{% endblock %}
{% block content %}
<h1>Post 입력 화면</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="id_image">이미지</label>
        {% if post.image %}
            <p>현재: <a href="{{post.image.url}}">{{post.image.name}}</a></p>
            <p>변경: <input type="file" name="image" accept="image/" id="id_image"></p>
        {% else %}
            <input type="file" name="image" accept="image/" id="id_image">
        {% endif %}
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10">
            {%if post%}
                {{post.content}}
            {%endif%}
        </textarea>
    </div>
    <div>
        <input type="submit">
    </div>

</form>
{% endblock %}

liongram/templates/posts/post_form2.html
{% extends 'base.html' %}
{% block title %}입력{% endblock %}
{% block content %}
<h1>Post 입력 화면</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <div>
        <input type="submit">
    </div>

</form>
{% endblock %}

liongram/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}목록{% endblock %}
{% block content %}
<h1>Post 목록 화면</h1>
{% for post in post_list %}
<div>
    {{ post.id }}</br>
    {{ post.image }}</br>
    {{ post.content }}</br>
    {{ post.created_at }}</br>
    {{ post.writer }}</br>
</div>
{% endfor %}
{% endblock %}